# Generated by Django 5.1.3 on 2024-11-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("name", "city"), name="unique_location"
            ),
        ),
    ]
