# Generated by Django 5.1.3 on 2024-11-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_location_unique_location"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "state"), name="unique_city"
            ),
        ),
    ]
