# Generated by Django 5.1.3 on 2024-11-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_city_unique_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="weatherreport",
            name="city",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="location.city"
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_state"
            ),
        ),
    ]
