# Generated by Django 5.1.3 on 2024-11-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_alter_country_name_alter_weatherreport_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
            preserve_default=False,
        ),
    ]
