# Generated by Django 5.1.3 on 2024-11-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_url', models.URLField()),
                ('posted_at', models.DateField()),
                ('url', models.URLField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
