services:
  postgres:
    image: "postgres:15.6-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
  redis:
    image: "redis:7.4.0-alpine"
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
  web:
    build: .
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
